require 'spree_core'
require 'spree_controllers_with_callbacks/engine'
require 'spree_controllers_with_callbacks/controller_callback'

require 'spree_controllers_with_callbacks/controllers/spree/taxons_controller_decorator'
require 'spree_controllers_with_callbacks/controllers/spree/products_controller_decorator'
